my_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: pedrocaroli
      password: Btrb0130##
      port: 5432
      dbname: db_projeto_1
      schema: dev
    prod:
      type: postgres
      host: postgres
      user: pedrocaroli
      password: Btrb0130##
      port: 5432
      dbname: db_projeto_1
      schema: prod
